platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: pipelines

outputs:
  - name: build-output

run:
  path: "pipelines/concourse/workspace/tasks/build.sh"