platform: linux

image_resource:
  type: docker-image
  source: {repository: quay.io/cosee-concourse/dind, tag: latest}

inputs:
  - name: sb-sample-service
  - name: pipelines

run:
  path: "pipelines/concourse/workspace/tasks/deploy.sh"