---
resources:
  - name: sb-sample-service
    type: git
    source:
      uri: https://github.com/kondoumh/sb-sample-service.git
      branch: master
  - name: pipelines
    type: git
    source:
      uri: https://github.com/kondoumh/pipelines.git
      branch: master

jobs:
- name: build-sb-sample
  public: true
  plan:
  - get: sb-sample-service
  - get: pipelines
  - task: Build project
    file: pipelines/concourse/workspace/tasks/build.yml
  - task: Deploy service
    privileged: true
    file: pipelines/concourse/workspace/tasks/deploy.yml